## PANDAS

In [18]:
import pandas as pd

In [19]:
a = [3, 4, 78, 501]
b = [92, 108, 6, 4079]
c = [38, 203, 96, 335]

In [20]:
box = pd.DataFrame({"a": a, "b": b, "c": c})

In [21]:
type(box)

pandas.DataFrame

In [22]:
print(box)

     a     b    c
0    3    92   38
1    4   108  203
2   78     6   96
3  501  4079  335

In [23]:
box

     a     b    c
0    3    92   38
1    4   108  203
2   78     6   96
3  501  4079  335

In [24]:
# data frame and dictionary are very similar structurally. essentially just fed it a dictionary and it's turned it into a nice little dataframe box

In [25]:
dir(box)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'a',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'b',
 'between_time',
 'bfill',
 'boxplot',
 'c',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [26]:
#now we want to get the data out again

box["a"]

0      3
1      4
2     78
3    501
Name: a, dtype: int64

In [27]:
d = box["a"]

In [28]:
type(d)

pandas.Series

In [29]:
e = list(d)

In [30]:
e

[3, 4, 78, 501]

In [31]:
a == e
# == means something is identical

True

In [33]:
box["row_mean"] = box.mean(axis=1)

In [34]:
box

     a     b    c     row_mean
0    3    92   38    44.333333
1    4   108  203   105.000000
2   78     6   96    60.000000
3  501  4079  335  1638.333333

In [65]:
df = pd.read_csv("/work/E26-experimental-psycholinguistics/Stroop-raw-over-the-years.csv")
# to import data from a csv file. 
# copy path, start with /work/

In [66]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [67]:
# to find the mean reading time:
df["meanRT"] = df.mean(axis=1)
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year   meanRT
0             4.16        6.76          4.45         4.65  2015  407.004
1             4.35        7.73          4.78         4.46  2015  407.264
2             3.60        7.00          4.00         3.50  2015  406.620
3             3.90        9.03          4.60         6.30  2015  407.766
4             4.22        9.98          6.83         6.24  2015  408.454
..             ...         ...           ...          ...   ...      ...
200           4.77       10.00          5.66         6.24  2025  410.334
201           4.61       12.80          6.87         9.55  2025  411.766
202           4.79       10.72          5.64         7.25  2025  410.680
203           4.41        8.87          6.70         6.70  2025  410.336
204           5.50        9.80          6.20        21.70  2025  413.640

[205 rows x 6 columns]

In [72]:
# to get rid of the year
df = df.drop(["Year"],axis=1)
df
# it's giving me an error to say year doesnt exist as if i didnt know that! i got rid of it!

KeyError: "['Year'] not found in axis"

In [71]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   meanRT
0             4.16        6.76          4.45         4.65  407.004
1             4.35        7.73          4.78         4.46  407.264
2             3.60        7.00          4.00         3.50  406.620
3             3.90        9.03          4.60         6.30  407.766
4             4.22        9.98          6.83         6.24  408.454
..             ...         ...           ...          ...      ...
200           4.77       10.00          5.66         6.24  410.334
201           4.61       12.80          6.87         9.55  411.766
202           4.79       10.72          5.64         7.25  410.680
203           4.41        8.87          6.70         6.70  410.336
204           5.50        9.80          6.20        21.70  413.640

[205 rows x 5 columns]